#!/bin/bash
echo "Content-type: text/html"
echo ''
whoami
echo ''
echo $WORKSPACE_NAMESPACE
echo 'was found in:'
echo ''
env
echo ''
echo 'having started with:'
echo ''
echo $WHOAMI
echo ''
echo $STARTING_ENV
echo ''
echo 'where: '
echo ''
echo $(cat /etc/apache2/envvars)
echo ''
echo $(tnu drs --help)
echo ''
echo $(tnu drs info   "drs://dg.4503:dg.4503/fa640b0e-9779-452f-99a6-16d833d15bd0"  2>&1 > /dev/null)
echo ''
echo $(tnu drs access "drs://dg.4503:dg.4503/fa640b0e-9779-452f-99a6-16d833d15bd0")
echo ''




#!/usr/bin/env python3
# import os, traceback
# from terra_notebook_utils import drs
# print("content-type: text/plain")

# print("Content-Type: text/html;charset=utf-8")
# print("Content-type:text/html\r\n")
# print("<H1>" + os.environ.get("WORKSPACE_NAME") + "</H1>")

# try:
#     if not os.environ.get('WORKSPACE_NAME'):
#         raise RuntimeError('{} not found'.format(os.environ.get('WORKSPACE_NAME')))
#     if not os.environ.get('WORKSPACE_NAMESPACE'):
#         raise RuntimeError('{} not found'.format(os.environ.get('WORKSPACE_NAMESPACE')))
#     print(drs.access(drs_url='drs://dg.4503:dg.4503/fa640b0e-9779-452f-99a6-16d833d15bd0', workspace_namespace=os.environ.get('WORKSPACE_NAMESPACE'), workspace_name=os.environ.get('WORKSPACE_NAME')))
# except Exception as e:
#     print(traceback.print_exc())
